server:
  port: 8080

spring:
  application:
    name: dsms-backend
  
  # H2数据库配置
  datasource:
    url: jdbc:h2:file:./data/dsmsdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: dsms
    password: dsms
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      platform: h2
    
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# 日志配置
logging:
  level:
    root: INFO
    io.github.luolong47: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG